/**
 * GoQii Market Research Insights
 *
 * Market size, growth, and company analysis for M&A targets
 * in the fitness and activity tracking space.
 */

export interface MarketInsight {
  title: string;
  content: string;
  sources?: string[];
}

export interface MarketOverviewData {
  numberOfCompanies: number;
  marketSize: string;
  growthRate: string;
  insights: {
    companies: MarketInsight;
    marketValue: MarketInsight;
    growthRate: MarketInsight;
  };
}

export const goqiiMarketInsights: MarketOverviewData = {
  numberOfCompanies: 200,
  marketSize: "$10.59B",
  growthRate: "12%-28%",

  insights: {
    companies: {
      title: "Number of Companies",
      content: `To estimate the number of companies that could be M&A targets for Goqii in the space of "Fitness and Activity Tracker Companies" specifically focusing on "Mobile Fitness Tracking App Developers," I will use the following approach:

**Definition and Scope:**

"Mobile Fitness Tracking App Developers" means companies whose primary product is a mobile app for fitness/activity tracking (e.g., steps, calories, workouts, running, cycling, etc.), not just hardware (wearables).

Exclude giants (Apple, Google, Samsung) and focus on independent companies and startups—potentially realistic M&A targets.

Include both B2C and B2B (white-label, corporate wellness) players.

**Market Overview:**

There are thousands of fitness apps in Apple App Store and Google Play, but most are small or individual projects, not "companies."

Industry reports (e.g., Sensor Tower, App Annie) suggest there are hundreds of significant fitness tracking apps published by registered companies, but many are not independent or are too small (1-2 people).

Crunchbase/CB Insights/SimilarWeb list ~500–1000 companies globally in "Fitness Technology" or "Fitness Apps," but only a subset focus on mobile activity tracking (not diet, meditation, etc.).

**Refining the Estimate:**

- Remove companies focused only on nutrition, meditation, or single-sport niche (e.g., only yoga, only boxing).
- Remove companies that are merely marketing agencies or resellers.
- Remove companies already acquired or merged into larger platforms.
- Estimate that about 30–40% of "fitness app" companies focus on "activity tracking" (steps, runs, workouts, etc.).
- Assume that, globally, there are about 300–400 independent companies with a mobile app as a primary product in this niche.

**Filtering for M&A Suitability:**

- Remove companies that are too small (solo devs without a company), too large, or not active anymore.
- Final, realistic M&A target pool: 150–250 companies worldwide.

**Total Estimate:**

There are approximately **200 companies globally** that are independent, active, and primarily focused on developing mobile fitness/activity tracking apps, fitting the profile for M&A targets for Goqii.`,
      sources: []
    },

    marketValue: {
      title: "Market Value (USD)",
      content: `The most recent and authoritative estimate for the total market value of mobile fitness tracking app developers—which includes M&A targets relevant to Goqii in the fitness and activity tracker sector—is approximately **USD 10.59 billion globally in 2024**, with projections to grow to **USD 33.58 billion by 2033** at a CAGR of about **13.6%**.

**Key details supporting this estimate:**

- The global fitness app market size (covering exercise, weight loss, diet, nutrition, and activity tracking apps) was valued at USD 10.59 billion in 2024.
- The U.S. fitness app market alone was valued at USD 568 million in 2024, expected to grow to nearly USD 2 billion by 2033.
- Other sources estimate the global fitness app market around USD 8.3 to 15 billion in 2025, reflecting some variation depending on scope and segmentation.
- The market growth is driven by rising health awareness, smartphone and wearable adoption, and technological advances such as AI personalization and IoT integration.

Since Goqii operates in the fitness and activity tracking space with a focus on mobile fitness tracking apps, the USD 10.59 billion global fitness app market size in 2024 is the most relevant and recent figure for the total market value of potential M&A targets in this segment.

This figure represents the overall market size, which includes revenues generated by app developers, and thus indicates the scale of acquisition opportunities for companies like Goqii targeting mobile fitness tracking app developers.

**In summary:**

| Market Segment | Estimated Market Value (USD) | Year | Source |
|----------------|----------------------------|------|--------|
| Global Fitness App Market (all types) | 10.59 billion | 2024 | [1] |
| U.S. Fitness App Market | 568 million | 2024 | [3] |
| Global Fitness App Market (alternate) | 8.3 - 15 billion | 2025 | [5][7] |

The USD 10.59 billion (2024) figure is the most precise and recent comprehensive estimate for the market relevant to Goqii's M&A targets in mobile fitness tracking app development.`,
      sources: [
        "https://www.grandviewresearch.com/industry-analysis/fitness-app-market",
        "https://www.fitbudd.com/post/50-fitness-app-statistics-revenue-market-size-usage-more-in-2025",
        "https://www.imarcgroup.com/united-states-fitness-app-market",
        "https://sensortower.com/blog/state-of-mobile-health-and-fitness-in-2025",
        "https://quanrio.com/mobile-app-development/how-profitable-is-fitness-and-health-app-development/",
        "https://www.daffodilsw.com/fitness-app-development/",
        "https://vocal.media/writers/top-fitness-app-development-company-you-should-know-market-update-2025"
      ]
    },

    growthRate: {
      title: "Growth Rate (CAGR)",
      content: `To determine the annual growth rate (CAGR) for the market related to "M&A Targets for the company Goqii (goqii.com) >> Fitness and Activity Tracker Companies >> Mobile Fitness Tracking App Developers," we need to look at the broader fitness app market, as specific data for this niche might not be readily available. Here are some relevant CAGR forecasts for the fitness app market:

**Global Fitness Apps Market:**

- CAGR of **12.5%** from 2025 to 2035, according to Future Market Insights.
- CAGR of **27.45%** from 2025 to 2033, as reported by Market Data Forecast.
- CAGR of **13.59%** from 2025 to 2033, according to Grand View Research.

**Smart Fitness Apps Market:**

- CAGR of **18.4%** from 2024 to 2033.

**General Fitness Apps Market:**

- CAGR of **17.6%** from 2023 to 2030.

**Statista's Forecast:**

- CAGR of **3.56%** from 2025 to 2030 for the Fitness Apps market.

Given these forecasts, the most recent and relevant CAGR for the broader fitness app market, which includes mobile fitness tracking app developers, ranges from **12.5% to 27.45%** depending on the source and forecast period. The highest growth rate is reported by Market Data Forecast for the period 2025-2033.

For M&A targets specifically related to Goqii, these broader market trends can provide a general indication of growth potential, but specific CAGR figures for this niche might require more detailed market research.`,
      sources: [
        "https://www.futuremarketinsights.com/reports/fitness-apps-market",
        "https://www.marketdataforecast.com/market-reports/fitness-app-market",
        "https://www.grandviewresearch.com/industry-analysis/fitness-app-market",
        "https://www.grandviewresearch.com/industry-analysis/us-fitness-apps-market-report",
        "https://www.imarcgroup.com/united-states-fitness-app-market",
        "https://media.market.us/smart-fitness-apps-market-news/",
        "https://www.statista.com/outlook/hmo/digital-health/digital-fitness-well-being/health-wellness-coaching/fitness-apps/worldwide",
        "https://www.fitbudd.com/post/50-fitness-app-statistics-revenue-market-size-usage-more-in-2025"
      ]
    }
  }
};
